### ISSUE TITLE
Organización_Proyecto_Final

### ISSUE THREAD

**Issue by LLop8029** [LeonardoDPantoja/Final_Project#1]
Buenas Tardes Compañeros 

un recordatorio de la distribución de las Actividades el proyecto final:

[disita](https://github.com/disita)  Punto 5 Desarrollo de mapas en Python con GeoPandas o Folium.
[LLop8029](https://github.com/LLop8029) Punto 1 Mostrar visualizaciones interactivas usando Altair.
[LeonardoDPantoja](https://github.com/LeonardoDPantoja) Creación de reposotorio, Archivo markdown con el detalle de resultados y
Divulgación del proyecto.

Punto pendientes para completar actividad:
2. Consultar información de redes sociales y/o en el web usando un scraper.
3. Hacer preprocesamiento o análisis de texto utilizando string methods, regex, spaCy y/o NLTK.
4. Utilizar herramientas de análisis de texto como n-grams, wordclouds y/o análisis de sentimiento.
6. Usar herramientas de ChatGPT en Python.

Adicional tengo entendido que al repositorio se le debe dar un nombre en relación al análisis.
Mi propuesta es:   Análisis de las ventas generales y gastos en servicios de Telecom de la empresa "Venta de Diversos Productos*".

*El nombre es fictisio ya que no permitieron el uso del nombre comercial de la empresa.

**Comment by LeonardoDPantoja** [comment]
Listo
